export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOADING_START = 'LOADING_START';
export const LOADING_STOP = 'LOADING_STOP';
// export const IS_LOADING_START = 'IS_LOADING_START';
// export const IS_LOADING_STOP = 'IS_LOADING_STOP';
// export const IS_LOADING_START_LOGIN = 'IS_LOADING_START_LOGIN';
// export const IS_LOADING_STOP_LOGIN = 'IS_LOADING_STOP_LOGIN';
export const GET_PROFILE = 'GET_PROFILE';
export const ADD = 'GET_PROFILE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


export const IS_FIRST = 'IS_FIRST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const IS_LOADING_START = 'IS_LOADING_START';
export const IS_LOADING_STOP = 'IS_LOADING_STOP';

export const IS_LOGIN_LOADING_START = 'IS_LOGIN_LOADING_START';
export const IS_LOGIN_LOADING_STOP = 'IS_LOGIN_LOADING_STOP';